#!/usr/bin/env python

import hah

if __name__ == "__main__":
    # TODO> put nick, channel & servers in config.
	nick    = 'hah'
	channel = '#bot.slacker.se'
	server  = 'localhost'
	bot = hah.Hah(nick, channel, server)
	bot.unleash()
