#!/usr/bin/env python

import hah

if __name__ == "__main__":
	nick    = 'hah'
	channel = '#bot.slacker.se'
	server  = 'localhost'
	# twitter credentials.
	user = ''
	pwd = ''

	bot = hah.Hah(nick, channel, server, user, pwd)
	bot.unleash()
